### ISSUE TITLE
tasks todo

### ISSUE THREAD

**Issue by yosef406** [Fullstack-Alfanar/team-work1#1]
1. create files

- [x] index.html
- [x] dashboard.html
- [x] forgotPassword.html
- [x] signin.html
- [x] signup.html
- [x] style.scss
- [x] script.js
- [x] create design
- [x] readme

3. create html pages

- [x] index.html 
- [x] dashboard.html
- - [x] web size
- - [x] phone size
- [x] forgotPassword.html
- - [x] web size
- - [x] phone size
- [x] signin.html
- - [x] web size
- - [x] phone size
- [x] signup.html
- - [x] web size
- - [x] phone size

4. sub tasks for index.html

- [x] check in  cookies 
- - [x] index reroute to sign in (in case the user is not signed in)
- - [x] index reroute dashboard (in case the user is already signed in)

5. sub tasks for sign in page

- [x] style for web screen 
- [x] style for phone screen
- [x] style for tablet screen 
- [x] html elements 
- [x] sing in button functionality 
- - [x] validation
- - [x] add to  cookies
- - [x] check local storage
- - [x] reroute to dashboard
- - [x] display Error in case invalid info 
- [x] sign up button functionality
- - [x] reroute to sign up page (can be a href)
- [x] forgot password functionality
- - [x] reroute to forgotPassword page (can be a href)

6. sub tasks for sign up page

- [x] style for web screen
- [x] style for phone screen
- [x] style for tablet screen
- [x] html elements 
- [x] back button
- - [x] reroute to sign in
- [x] sign up button 
- - [x] validation
- - [x] add to local storage
- - [x] reroute to dashboard  (after sign up)

7. sub tasks for forgot password page

- [x] style for web screen
- [x] style for phone screen
- [x] style for tablet screen
- [x] html elements 
- [x] renew password button functionality

8. sub tasks for dashboard page

- [x] style for web screen
- [x] style for phone screen
- [x] style for tablet screen
- [x] html elements 
- [x] create dynamic user
- - [x] sign out button functionality

**Comment by yosef406** [comment]
local storage: 
**Key: ** "registeredUsers"
**Build:**
`
usersList =[ ]; 
user={  Email : "example@domain.com", Password : "123Pass" };
`
password must be at least 6 charterers.

**Comment by yosef406** [comment]
cookies:
when user signs in the id (email) is saved to cookies as signed in
there can be only one user signed in at a time.
` document.cookie = " signedInUser = email.domain.com; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/ "; `

**Comment by yosef406** [comment]
the work is done
